import { jsPDF } from 'jspdf';
import { Transaction } from './tx-classifier';

export interface LegalSection {
  exhibitNumber: string;
  paragraphNumber: number;
  legalProse: string;
  txHashes: string[];
  dateRange: string;
}

function addWatermark(doc: jsPDF): void {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFont('times', 'italic');
  doc.setFontSize(14);
  doc.setTextColor(195, 195, 195);
  doc.text(
    'Generated by LexExhibit for BLI Hackathon',
    pageWidth / 2,
    pageHeight / 2,
    { angle: 45, align: 'center' }
  );
}

function addLineNumbersAndMargins(doc: jsPDF): void {
  doc.setFont('times', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(160, 160, 160);
  for (let i = 1; i <= 28; i++) {
    doc.text(i.toString(), 0.5, 1 + (i * 0.33));
  }
  doc.setTextColor(0, 0, 0);
  doc.setLineWidth(0.01);
  doc.line(1, 1, 1, 10.5);
  doc.line(8, 1, 8, 10.5);
}

function resetBodyFont(doc: jsPDF): void {
  doc.setFont('times', 'normal');
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
}

const CATEGORY_STYLES: Record<string, {
  fill: [number, number, number];
  text: [number, number, number];
  label: string;
}> = {
  mixer_interaction: { fill: [255, 187, 107], text: [140, 60, 0],   label: 'MIXER (TORNADO)' },
  swap:              { fill: [167, 243, 208], text: [5, 120, 60],    label: 'DEX SWAP' },
  bridge:            { fill: [186, 214, 255], text: [30, 64, 175],   label: 'BRIDGE CONTRACT' },
  lp_deposit:        { fill: [216, 180, 254], text: [109, 40, 217],  label: 'LP DEPOSIT' },
  lp_withdraw:       { fill: [216, 180, 254], text: [109, 40, 217],  label: 'LP WITHDRAW' },
  transfer:          { fill: [228, 228, 231], text: [63, 63, 70],    label: 'TRANSFER' },
  contract_call:     { fill: [228, 228, 231], text: [63, 63, 70],    label: 'CONTRACT CALL' },
  unknown:           { fill: [228, 228, 231], text: [63, 63, 70],    label: 'UNKNOWN' },
};

function drawFundFlowPage(doc: jsPDF, transactions: Transaction[]): void {
  doc.addPage();
  addWatermark(doc);

  doc.setFont('times', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(0, 0, 0);
  doc.text('EXHIBIT Z — FORENSIC FUND FLOW VISUALIZATION', 4.25, 1.0, { align: 'center' });

  doc.setFont('times', 'italic');
  doc.setFontSize(9);
  doc.setTextColor(80, 80, 80);
  doc.text('Node-link diagram of on-chain asset movements. Each arrow represents one transaction.', 4.25, 1.28, { align: 'center' });

  const maxNodes = Math.min(transactions.length, 5);
  const sourceX = 1.0;
  const sourceW = 1.5;
  const sourceH = 0.65;
  const nodeW = 1.5;
  const nodeH = 0.65;
  const destX = 5.5;
  const totalGridH = maxNodes * 1.1;
  const gridStartY = 2.0;
  const sourceY = gridStartY + totalGridH / 2 - sourceH / 2;
  const midX = (sourceX + sourceW + destX) / 2;

  // Source node
  doc.setDrawColor(161, 110, 0);
  doc.setFillColor(255, 237, 213);
  doc.roundedRect(sourceX, sourceY, sourceW, sourceH, 0.08, 0.08, 'FD');
  doc.setFont('times', 'bold');
  doc.setFontSize(7);
  doc.setTextColor(130, 65, 0);
  doc.text('TARGET WALLET', sourceX + sourceW / 2, sourceY + 0.24, { align: 'center' });

  const from = transactions[0].from;
  const shortFrom = from.length > 14 ? from.slice(0, 8) + '…' + from.slice(-6) : from;
  doc.setFont('times', 'normal');
  doc.setFontSize(6);
  doc.setTextColor(80, 80, 80);
  doc.text(shortFrom, sourceX + sourceW / 2, sourceY + 0.44, { align: 'center' });

  // Destination nodes + connecting arrows
  for (let i = 0; i < maxNodes; i++) {
    const tx = transactions[i];
    const nodeY = gridStartY + i * 1.1;
    const srcAnchorY = sourceY + sourceH / 2;
    const dstAnchorY = nodeY + nodeH / 2;
    const style = CATEGORY_STYLES[tx.category] ?? CATEGORY_STYLES.unknown;

    // L-shaped arrow: source right → midX → dest
    doc.setDrawColor(180, 180, 180);
    doc.setLineWidth(0.013);
    doc.line(sourceX + sourceW, srcAnchorY, midX, srcAnchorY);
    doc.line(midX, srcAnchorY, midX, dstAnchorY);
    doc.line(midX, dstAnchorY, destX, dstAnchorY);
    // Arrowhead
    doc.line(destX, dstAnchorY, destX - 0.08, dstAnchorY - 0.05);
    doc.line(destX, dstAnchorY, destX - 0.08, dstAnchorY + 0.05);

    // ETH value label on arrow
    const valEth = parseFloat(tx.value || '0').toFixed(2);
    doc.setFont('times', 'italic');
    doc.setFontSize(6.5);
    doc.setTextColor(90, 90, 90);
    const labelY = Math.min(srcAnchorY, dstAnchorY) - 0.04;
    doc.text(`${valEth} ETH`, midX, labelY, { align: 'center' });

    // Destination node
    doc.setDrawColor(style.text[0] >> 1, style.text[1] >> 1, style.text[2] >> 1);
    doc.setFillColor(style.fill[0], style.fill[1], style.fill[2]);
    doc.roundedRect(destX, nodeY, nodeW, nodeH, 0.08, 0.08, 'FD');
    doc.setFont('times', 'bold');
    doc.setFontSize(7);
    doc.setTextColor(style.text[0], style.text[1], style.text[2]);
    doc.text(style.label, destX + nodeW / 2, nodeY + 0.24, { align: 'center' });
    doc.setFont('times', 'normal');
    doc.setFontSize(6);
    doc.setTextColor(70, 70, 70);
    const shortHash = tx.hash.slice(0, 10) + '…';
    doc.text(`Exhibit ${String.fromCharCode(65 + i)}: ${shortHash}`, destX + nodeW / 2, nodeY + 0.44, { align: 'center' });
  }

  if (transactions.length > 5) {
    doc.setFont('times', 'italic');
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text(
      `+ ${transactions.length - 5} additional transactions (see Exhibits above)`,
      4.25,
      gridStartY + maxNodes * 1.1 + 0.28,
      { align: 'center' }
    );
  }

  // Legend
  const legendY = 9.0;
  doc.setFont('times', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(0, 0, 0);
  doc.text('LEGEND:', 1.0, legendY);

  const legendItems = [
    { fill: CATEGORY_STYLES.mixer_interaction.fill, label: 'Mixer (HIGH RISK)' },
    { fill: CATEGORY_STYLES.swap.fill,              label: 'DEX Swap' },
    { fill: CATEGORY_STYLES.bridge.fill,            label: 'Bridge Contract' },
    { fill: CATEGORY_STYLES.transfer.fill,          label: 'Transfer' },
  ];

  legendItems.forEach((item, i) => {
    const lx = 1.0 + i * 1.85;
    doc.setFillColor(item.fill[0], item.fill[1], item.fill[2]);
    doc.setDrawColor(150, 150, 150);
    doc.rect(lx, legendY + 0.08, 0.18, 0.18, 'FD');
    doc.setFont('times', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(50, 50, 50);
    doc.text(item.label, lx + 0.25, legendY + 0.22);
  });
}

export async function generateAffidavitPdfBase64(sections: LegalSection[], transactions?: Transaction[]): Promise<string> {
  const doc = new jsPDF({
    unit: 'in',
    format: 'letter'
  });

  addWatermark(doc);
  addLineNumbersAndMargins(doc);
  resetBodyFont(doc);

  // Caption block
  doc.text('SUPERIOR COURT OF THE STATE OF CALIFORNIA', 1.5, 1.5);
  doc.text('COUNTY OF LOS ANGELES', 1.5, 1.83);

  doc.text('JOHN DOE, Plaintiff,', 1.5, 2.5);
  doc.text('v.', 2.5, 2.83);
  doc.text('JANE DOE, Defendant.', 1.5, 3.16);

  doc.text('Case No.: 26-FL-001234', 5.0, 2.5);
  doc.text('AFFIDAVIT OF BLOCKCHAIN', 5.0, 2.83);
  doc.text('ASSET TRACING', 5.0, 3.16);

  doc.setFont('times', 'bold');
  doc.text('DECLARATION UNDER PENALTY OF PERJURY', 1.5, 4.0);
  doc.setFont('times', 'normal');
  doc.text('I, LexExhibit Analyst, declare:', 1.5, 4.33);

  let cursorY = 5.0;

  sections.forEach((section, index) => {
    if (cursorY > 9.5) {
      doc.addPage();
      addWatermark(doc);
      addLineNumbersAndMargins(doc);
      resetBodyFont(doc);
      cursorY = 1.5;
    }

    const textLines = doc.splitTextToSize(`${index + 1}. ${section.legalProse}`, 6.0);
    doc.text(textLines, 1.5, cursorY);
    // 0.33" = 24pt baseline-to-baseline = true double-spacing for 12pt font
    cursorY += (textLines.length * 0.33) + 0.2;
  });

  cursorY += 0.5;
  if (cursorY > 9.0) {
    doc.addPage();
    addWatermark(doc);
    addLineNumbersAndMargins(doc);
    resetBodyFont(doc);
    cursorY = 1.5;
  }

  doc.text('I declare under penalty of perjury under the laws of the State of', 1.5, cursorY);
  doc.text('California that the foregoing is true and correct.', 1.5, cursorY + 0.33);
  doc.text('Executed on November 1, 2026.', 1.5, cursorY + 0.66);
  doc.text('_____________________________', 5.0, cursorY + 1.0);
  doc.text('LexExhibit Analyst', 5.0, cursorY + 1.33);

  if (transactions && transactions.length > 0) {
    drawFundFlowPage(doc, transactions);
  }

  const b64 = btoa(doc.output());
  return `data:application/pdf;base64,${b64}`;
}
